// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCcSxasjecuG8zixs1CgYMc5gl3nHcgww',
    appId: '1:195325558436:web:43d99ea9fee7857392b031',
    messagingSenderId: '195325558436',
    projectId: 'food-ordering-app-2318d',
    authDomain: 'food-ordering-app-2318d.firebaseapp.com',
    storageBucket: 'food-ordering-app-2318d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwPKAR5C32UD8lEkek2OPzfWlBqMQU1Sw',
    appId: '1:195325558436:android:654fd10ec46e415e92b031',
    messagingSenderId: '195325558436',
    projectId: 'food-ordering-app-2318d',
    storageBucket: 'food-ordering-app-2318d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhLmXH7qiO2fxWayeV1UEzoSZcuXkmYSY',
    appId: '1:195325558436:ios:de08eb9cf805e51f92b031',
    messagingSenderId: '195325558436',
    projectId: 'food-ordering-app-2318d',
    storageBucket: 'food-ordering-app-2318d.firebasestorage.app',
    iosBundleId: 'com.example.foodOrderingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhLmXH7qiO2fxWayeV1UEzoSZcuXkmYSY',
    appId: '1:195325558436:ios:de08eb9cf805e51f92b031',
    messagingSenderId: '195325558436',
    projectId: 'food-ordering-app-2318d',
    storageBucket: 'food-ordering-app-2318d.firebasestorage.app',
    iosBundleId: 'com.example.foodOrderingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCcSxasjecuG8zixs1CgYMc5gl3nHcgww',
    appId: '1:195325558436:web:407ded325b47c67392b031',
    messagingSenderId: '195325558436',
    projectId: 'food-ordering-app-2318d',
    authDomain: 'food-ordering-app-2318d.firebaseapp.com',
    storageBucket: 'food-ordering-app-2318d.firebasestorage.app',
  );
}
